### ISSUE TITLE
Option to over ride any of the renderer

### ISSUE THREAD

**Issue by atulmy** [BomdiZane/EditorJS-React-Renderer#10]
Wondering if there is an option to over ride any of the renderer provided by this library.

For example, option to customize render function of `renderers/imageOutput` only.

**Comment by dev-juju** [comment]
Hi @atulmy 

You can customize how the renderers render your elements by passing a style object to the respective renderers. 
We provide a connection to every rendered element, their wrappers, siblings and sub-elements such that you have full control over the rendered element's look. 

We think this is enough for almost all cases and unfortunately at this time we do not see much of a need for your requested functionality as it kind of defeats the whole purpose of the library to begin with (you do not have to write render functions).

We hope you find an easier way to satisfy your use case.

Thanks for your contribution
