### ISSUE TITLE
Linebreaks are missing

### ISSUE THREAD

**Issue by serg-kan** [BomdiZane/EditorJS-React-Renderer#12]
Hello!

Your tool is super cool, but I have a problem, maybe you could help me

I am using react-editor-js tool to use Editor.js and pass data from it to your tool.
For some reason linebreaks are missing but the output object (from react-editor-js) seems to be correct (like in your example)

![image](https://user-images.githubusercontent.com/52253662/87703215-25714b80-c7a3-11ea-85d2-76ba47109d18.png)
![image](https://user-images.githubusercontent.com/52253662/87703293-42a61a00-c7a3-11ea-88b2-4a677e133615.png)

Do you know what can be wrong?

Thank you in advance!

**Comment by dev-juju** [comment]
Hi @serg-kan 

Please note that for the example block you have there, the parser would return 3 consecutive paragraph elements.
These are not wrapped in any container (we let you decide how you want to place/position these elements on your page).

By default, browsers add a blank line before and after paragraph elements, so each should be on a separate line, with reasonable margins.

Please check the following:

- Do you have any CSS Reset or predefined styles in your project tree that might affect default paragraph rendering?

- Is your container/wrapper a flex box? If so you might want to set the flex-direction property to "column". 


If none of the above resolves your issue, you can force each paragraph element returned by the parser to occupy the full width of it's parent/wrapper by passing a style object to the render method you use

`
ParagraphOutput(data, { width: '100%' });

Or

Output(data, { paragraph: { width: '100%' }});
`

Please use chrome/firefox devtools to inspect the styles applied to your elements and see if there are any overrides.

**Comment by serg-kan** [comment]
Got it, thank you!
The problem was in me
