### ISSUE TITLE
Output with a custom block tool

### ISSUE THREAD

**Issue by danhttdev** [BomdiZane/EditorJS-React-Renderer#16]
In docs of Editorjs, it has a custom block tool section. Then, I created a block that i built myself. And I don't see any about this in the doc of this package

![image](https://user-images.githubusercontent.com/33081945/90252561-ea2d6f80-de69-11ea-9f3b-0232ef3731f3.png)

Here is my custom block type
![image](https://user-images.githubusercontent.com/33081945/90252811-59a35f00-de6a-11ea-96f5-177ce8e59dc9.png)

**Comment by dev-juju** [comment]
@ttd1997 

If you created your own block, you need to create your own renderer.
Please see our README.MD for blocks we support.
