### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by danhttdev** [BomdiZane/EditorJS-React-Renderer#17]
![image](https://user-images.githubusercontent.com/33081945/90253188-f665fc80-de6a-11ea-94fe-101f4d08b7c8.png)
![image](https://user-images.githubusercontent.com/33081945/90253222-01b92800-de6b-11ea-80cc-b37ca328a5c3.png)

**Comment by dev-juju** [comment]
@ttd1997 

What renderer throws this warning? Please make sure the warning was caused by EER, not by your own code.
What does your block data look like?

This issue lacks adequate information and will be closed.

**Comment by danhttdev** [comment]
> @ttd1997
> 
> What renderer throws this warning? Please make sure the warning was caused by EER, not by your own code.
> What does your block data look like?
> 
> This issue lacks adequate information and will be closed.

![image](https://user-images.githubusercontent.com/33081945/90304292-695d8a80-dee0-11ea-89eb-71ddec97c524.png)
![image](https://user-images.githubusercontent.com/33081945/90304314-99a52900-dee0-11ea-8299-8dc532e9eb5f.png)
