### ISSUE TITLE
Tables render are Editable?

### ISSUE THREAD

**Issue by adshin21** [BomdiZane/EditorJS-React-Renderer#19]
Hello, I just visit your demo [page](https://err.bomdisoft.com/) went under **Paragraph with Table** and I can edit that table.
![image](https://user-images.githubusercontent.com/45573407/91608902-049c3880-e994-11ea-828f-2e2e89e4cf4d.png)
I'm just wondering is it a feature or a bug?

**Comment by dev-juju** [comment]
All edits are temporary...no one else see's that...just you. Those values will reset when you leave/reload the page
