### ISSUE TITLE
Resolve warning for child unique key in a list

### ISSUE THREAD

**Issue by sylvestermolina** [BomdiZane/EditorJS-React-Renderer#4]
Thank you for this library. I am currently trying to integrate it in my app and I would like to ask if we can resolve the warnings that shows regarding reacts child list key inside a loop https://fb.me/react-warning-keys

**Comment by dev-juju** [comment]
@sylvestermolina could you please provide some more details about this issue

- What specific output renderer is causing this warnings for you?
- Do you have a stacktrace of this warning? 
- Could you provide a copy of your block data or code?

Will will look into this once further information is provided

**Comment by idavydoff** [comment]
![image](https://user-images.githubusercontent.com/28686284/82065838-494adf00-96d7-11ea-9637-f622c78d315f.png)

**Comment by dev-juju** [comment]
This has been resolved in [v2.1.7](https://www.npmjs.com/package/editorjs-react-renderer)
Please update your package
