### ISSUE TITLE
Define class names for header levels

### ISSUE THREAD

**Issue by alvarolozano** [BomdiZane/EditorJS-React-Renderer#46]
**Is your feature request related to a problem? Please describe.**
When using TailwindCSS or other CSS frameworks, header tags (h1, h2, h3) do not have default styles. When I try to define the styles by using the `classNames` prop, with `{ header: 'text-xl '}`, it applies the same class for all the header levels, so they look the same

**Describe the solution you'd like**
When defining "header" styles, allow to pass an object with class name definitions for each level

```
header: {
   h1: 'text-3xl',
   h2: 'text-2xl',
   h3: 'text-xl'
}
```

**Comment by dev-juju** [comment]
Resolved by V3.1.0
