### ISSUE TITLE
Checkboxes and label throw errors in console

### ISSUE THREAD

**Issue by dcakmak** [BomdiZane/EditorJS-React-Renderer#48]
With the plugin version of Editor.js for Strapi, checkboxes can also be set. (Maybe also with the original version, I don't know right now).  Anyway, with React these still throw errors in the console.

`Warning: You provided a _checked_ prop to a form field without an _onChange_ handler. This will render a read-only field. If the field should be mutable use _defaultChecked_. Otherwise, set either _onChange_ or _readOnly_.`

Also the label element with the for tag
`Warning: Invalid DOM property for. Did you mean htmlFor?`

**Comment by alvarolozano** [comment]
Same here!

I will try to fix the "HtmlFor" prop issue ASAP... The other one should be discussed (checkboxes should be readOnly??)

**Comment by dev-juju** [comment]
Console warnings have been resolved by V3.1.0

Checkboxes are readOnly as the library's purpose is rendering/displaying data/content, not editing. 
Editing should be handled by EditorJS or any other editor of choice.
