### ISSUE TITLE
LinkTool error

### ISSUE THREAD

**Issue by AdversTM** [BomdiZane/EditorJS-React-Renderer#55]
LinkTool throws `TypeError: Cannot read properties of undefined (reading 'url')`
when passing the following data:
`{
  link: "https://example.com",
  meta: {
    title: "Example"
  }
}`
Probably missing `?` here: https://github.com/dev-juju/EditorJS-React-Renderer/blob/fb90c8cab4d04c0d5fc3f3e1db4e181debf21ce8/renderers/linkTool/index.tsx#L50

**Comment by dev-juju** [comment]
Resolved in V3.3.0
