### ISSUE TITLE
Video render doesn't output anything

### ISSUE THREAD

**Issue by pacid** [BomdiZane/EditorJS-React-Renderer#59]
Hi, 

I use the renderer to display images - and it works fine. The image html is rendered. However when attaching a video nothing gets rendered from the output data. And when adding it via editor.js it works fine - vid uploads, html rendered, you can play the video.

![image](https://user-images.githubusercontent.com/1618052/184535628-78d7ea08-075c-407f-8efc-2673f1e9b44d.png)

![image](https://user-images.githubusercontent.com/1618052/184535639-f05055d0-7ede-4111-b142-4a44cc57561f.png)

This is html rendered for an image:
![image](https://user-images.githubusercontent.com/1618052/184535667-5563d209-7f06-4b79-a244-76b9d83ed9fd.png)

![image](https://user-images.githubusercontent.com/1618052/184535669-a294d2a2-fb26-4ba2-887e-c98878d0d396.png)

This is html rendered for a video. No video appears.
![image](https://user-images.githubusercontent.com/1618052/184535736-5336140f-326b-4956-9e52-45f39f4bfb72.png)

Thanks in advance for your help,
Pawel

**Comment by dev-juju** [comment]
@pacid 

Your video data uses an image format, which is incorrect.
Ideally the data passed to ERR should be generated by one of the editor.js plugins (See [Supported blocks](https://www.npmjs.com/package/editorjs-react-renderer) section on NPM). 

If your data is generated in other ways, it should take same format. 
For videos, see [Simple Video](https://github.com/PaulKinlan/simple-video) plugin and/or [Embed](https://github.com/editor-js/embed) plugin.

In this case (using pasted URLs), your data should look like this

```typescript
type SimpleVideoData = {
  type: 'video'
  data: {
    url: string
    caption?: string
    autoplay?: bool
    controls?: bool
    muted?: bool
    stretched?: bool
  }
}
```

**Comment by pacid** [comment]
I am using 

``import VideoTool from "@weekwood/editorjs-video";``

as it allows to upload the videos and the simple one only "Works only with pasted videos and URLs and requires no server-side uploader"

Now switched to SimpleVideo, pasted the video and then rendered in a post it looks like that:
![image](https://user-images.githubusercontent.com/1618052/184555630-8ef6eced-d277-4194-b93d-68b50e83acc9.png)

On the site:
![image](https://user-images.githubusercontent.com/1618052/184555653-9c1a1b73-f795-40c8-9f56-7029692e7203.png)

Definitely would like to have some player here after the video file has been uploaded. I understand that I can create a custom renderer, would you recommend any 3rd party vid players that I could harness here and use on the site to embed it?

I would even use this one that is from the above library that I added. (this is when I am using ``@weekwood/editorjs-video``)
![image](https://user-images.githubusercontent.com/1618052/184555768-fc3dba11-e007-425f-b9cf-0524a3d750dd.png)
As it works okay. Just not sure how to go about adding it as a custom renderer.

I think it's this one https://github.com/CookPete/react-player, so might just add this as a renderer for this specific block.

Thanks for your help.

**Comment by dev-juju** [comment]
@pacid 

V3.5.0 should now have support for @weekwood/editorjs-video
