### ISSUE TITLE
Can you make this to be use in node for backend? I want to parse into html in nodejs

### ISSUE THREAD

**Issue by aayush2252** [BomdiZane/EditorJS-React-Renderer#61]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dev-juju** [comment]
@aayush2252 ERR is a React package (built with React for React), hence it is client-side. At this point we have no plans to make it run outside your browser.
