### ISSUE TITLE
Is this supposed to support custom block types?

### ISSUE THREAD

**Issue by timeisenhuth** [BomdiZane/EditorJS-React-Renderer#62]
I've implemented a custom renderer for a custom block plugin that I built but it doesn't render. Looking at the code I can see that if the renderer key doesn't match any it just returns an empty fragment?

**Comment by dev-juju** [comment]
@timeisenhuth 

V3.4.0 should allow you create custom renderers for unsupported blocks

**Comment by timeisenhuth** [comment]
@dev-juju Awesome, any timeline on that release?

**Comment by dev-juju** [comment]
Yesterday :)
