### ISSUE TITLE
@types for typescript app

### ISSUE THREAD

**Issue by ahmadxgani** [BomdiZane/EditorJS-React-Renderer#68]
I am use typescript for my react app, and the lint of typescript says:

```
Could not find a declaration file for module 'editorjs-react-renderer'. 'd:/GD Gani/From Github/blog/simple-blog-frontend/node_modules/editorjs-react-renderer/dist/index.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/editorjs-react-renderer` if it exists or add a new declaration (.d.ts) file containing `declare module 'editorjs-react-renderer';`
```

![image](https://user-images.githubusercontent.com/73988956/204072729-2e0ccb66-6f05-4832-8a62-e02edf921afc.png)

what best practice for the problem?

**Comment by dev-juju** [comment]
@QUERY-GANI 

V3.5.0 ships with types. Just update the package and the error should go away.
If you have to stay on older version for some reason, adding a declaration file would be your only option as I'm not sure @types/editorjs-react-renderer exists yet
