### ISSUE TITLE
Extremely large dist file

### ISSUE THREAD

**Issue by eurobob** [BomdiZane/EditorJS-React-Renderer#7]
This module is dominating my bundle size. Can we get a version on npm that is built for production?

![image](https://user-images.githubusercontent.com/4255350/84082541-ef88bc80-a9d7-11ea-9647-b56c62e5a60e.png)

**Comment by eurobob** [comment]
Made some small adjustments in #8 

However, the bundle size for even this module is still potentially nearly twice as big as it should be. The source map analysis for the dist.min.js in my PR has a large amount of code from an unknown source:

![image](https://user-images.githubusercontent.com/4255350/84084926-5e681480-a9dc-11ea-899e-83e5403ca135.png)

**Comment by dev-juju** [comment]
@eurobob this will be looked into once resources are freed up. In the meantime, a production build as you've done in this PR should improve the size

Thanks for your contribution.

**Comment by dev-juju** [comment]
Fixed by 3.0.0
