### ISSUE TITLE
Classes not getting added using classNames

### ISSUE THREAD

**Issue by tempcoderr** [BomdiZane/EditorJS-React-Renderer#70]
**Describe the bug**
I am using `Nextjs` with `TailwindCSS` and thus need to add classes to the components but they are not getting added, but styles are getting added. I have also checked this using the `useRef` hook.

**Expected behavior**
Classes should get added

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 3.5.0

**Additional context**
Here is my code:
```js
  const classes = {
    header: {
      h2: "text-red-500",
      h3: "text-red-500",
      h4: "text-red-500",
    },
    paragraph: "text-red-500",
  };

<section ref={sectionref}>
    <Output data={data} style={style} classNames={classes} />
</section>
```
Am i doing something wrong here?

**Comment by remoblaser** [comment]
Same here :(

Upon closer inspection I realized it's just the paragraph block that doesn't apply the classNames. I've created a PR with a fix.
Edit: While using the package I've also realized the header block doesn't render class names, fixed that as well in my PR.
