### ISSUE TITLE
"This browser does not support `document.implementation.createHTMLDocument`"

### ISSUE THREAD

**Issue by PCoder23** [BomdiZane/EditorJS-React-Renderer#78]
**Describe the bug**
I am encountering an issue with the "editorjs-react-renderer" package in a project that uses Next.js version 13.5.6. It appears that the document.implementation.createHTMLDocument method is not supported, which is causing a runtime error. This method is being used within the package, and it's not functioning as expected in my environment.

**To Reproduce**
1.Create a Next.js project with version 13.5.6.
2.Integrate the "editorjs-react-renderer" package.
3.pass the block data getting from editorjs to the Output comonent as prop  

**Expected behavior**
Unhandled Runtime Error
Error: This browser does not support `document.implementation.createHTMLDocument`
...

**Screenshots**
![Screenshot 2023-11-04 204255](https://github.com/dev-juju/EditorJS-React-Renderer/assets/85278795/bbac66b1-8abf-466c-8bdc-0e488a55512a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 3.5.1

**Comment by bastianrickmannACN** [comment]
@PCoder23 [ReadMe Server Side Rendering ]( https://github.com/dev-juju/EditorJS-React-Renderer?tab=readme-ov-file#server-side-rendering)

You are probably trying to use Server Side Rendering which isn't supported anymore since Version 3.0.0
